development:
  cloud_name: hdbnc6ura
  api_key: <%= ENV["CL_ID"] %>
  api_secret: <%= ENV["CL_KEY"] %>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: hdbnc6ura
  api_key: <%= ENV["CL_ID"] %>
  api_secret: <%= ENV["CL_KEY"] %>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: hdbnc6ura
  api_key: <%= ENV["CL_ID"] %>
  api_secret: <%= ENV["CL_KEY"] %>
  enhance_image_tag: true
  static_file_support: false